"""Generate bitmap glyphs for math symbols used in KhiCAS.

This is a Python replacement for the original ``gen_glyphs3.ps1`` PowerShell
script. It renders 14 math symbols from Noto Sans SC at 4 target sizes and
prints C-style byte arrays that can be pasted into
``System/applications/user/khicas/kcasporing_gl.c``.

The script follows the same algorithm as the PowerShell version (render large,
crop to bounding box, scale preserving aspect ratio, center, threshold) but uses
Pillow/FreeType instead of Windows GDI+. Because the two rasterizers differ,
the generated bytes are not guaranteed to be bit-identical to the PowerShell
output, but they are usable for the same purpose.

Run with uv from the repository root::

    uv run --project dev_tools dev_tools/gen_glyphs.py

Or from inside ``dev_tools/``::

    uv run gen_glyphs.py
"""

from __future__ import annotations

import argparse
import os
import platform
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

GLYPH_NAMES = [
    "pi",
    "sqrt",
    "integ",
    "infin",
    "leq",
    "geq",
    "neq",
    "arrow",
    "alpha",
    "beta",
    "theta",
    "Sigma",
    "times",
    "divide",
]

GLYPH_CODES = [
    0x03C0,
    0x221A,
    0x222B,
    0x221E,
    0x2264,
    0x2265,
    0x2260,
    0x2192,
    0x03B1,
    0x03B2,
    0x03B8,
    0x03A3,
    0x00D7,
    0x00F7,
]

SIZES = [
    (8, 5, "5x8"),
    (12, 6, "6x12"),
    (14, 7, "7x14"),
    (16, 8, "8x16"),
]

FONT_PATH = Path(__file__).resolve().parent.parent / "fonts" / "Assets" / "unifont-17.0.04.otf"


def find_font_path(font_name: str = "") -> Path:
    """Return the bundled unifont path regardless of ``font_name``."""
    path = FONT_PATH
    if not path.exists():
        raise FileNotFoundError(f"Bundled font not found at {path}")
    return path


def find_bounding_box(img: Image.Image, threshold: int) -> tuple[int, int, int, int]:
    """Return (left, top, right, bottom) bounding box of dark pixels."""
    pixels = img.load()
    width, height = img.size
    left = width
    right = 0
    top = height
    bottom = 0

    for y in range(height):
        for x in range(width):
            if pixels[x, y] < threshold:
                if x < left:
                    left = x
                if x > right:
                    right = x
                if y < top:
                    top = y
                if y > bottom:
                    bottom = y

    return left, top, right, bottom


def extract_bytes(img: Image.Image, width: int, height: int, threshold: int) -> list[int]:
    """Convert a grayscale image into a list of bytes (bit7 = leftmost pixel)."""
    pixels = img.load()
    out: list[int] = []
    for y in range(height):
        byte_val = 0
        for x in range(width):
            if pixels[x, y] < threshold:
                byte_val |= 0x80 >> x
        out.append(byte_val)
    return out


def render_glyph(
    code: int,
    name: str,
    target_h: int,
    target_w: int,
    label: str,
    font: ImageFont.FreeTypeFont,
    out_dir: Path,
    render_height: int,
    margin: int,
    threshold_bbox: int,
    threshold_extract: int,
    stroke_width: int,
) -> str:
    """Render one glyph and return the formatted C-array line."""
    char = chr(code)

    # Render large onto a white canvas with generous margins, matching the
    # original PowerShell script's layout.
    big_w = render_height + margin * 2
    big_h = render_height + margin * 2
    big_img = Image.new("L", (big_w, big_h), 255)
    draw = ImageDraw.Draw(big_img)
    kwargs: dict[str, object] = {"font": font, "fill": 0}
    if stroke_width:
        kwargs["stroke_width"] = stroke_width
        kwargs["stroke_fill"] = 0
    draw.text((margin, 0), char, **kwargs)

    # Crop to the actual glyph bounds.
    left, top, right, bottom = find_bounding_box(big_img, threshold_bbox)
    if left > right:
        left, top, right, bottom = 0, 0, target_w - 1, target_h - 1
    gh = bottom - top + 1
    gw = right - left + 1
    cropped = big_img.crop((left, top, right + 1, bottom + 1))

    # Scale preserving aspect ratio, fitting inside target_w x target_h.
    scale = min(target_w / gw, target_h / gh)
    dst_w = max(1, int(gw * scale))
    dst_h = max(1, int(gh * scale))
    scaled = cropped.resize((dst_w, dst_h), Image.Resampling.LANCZOS)

    # Paste centered onto the final target image.
    tar_img = Image.new("L", (target_w, target_h), 255)
    off_x = (target_w - dst_w) // 2
    off_y = (target_h - dst_h) // 2
    tar_img.paste(scaled, (off_x, off_y))

    # Save debug image.
    out_dir.mkdir(parents=True, exist_ok=True)
    tar_img.save(out_dir / f"{name}_{label}.png")

    # Extract bytes and format the C-array line.
    bytes_ = extract_bytes(tar_img, target_w, target_h, threshold_extract)
    hex_parts = ",".join(f"0x{b:02X}" for b in bytes_)
    return f"    /* {name:<6} */ {hex_parts},"


def main(argv: list[str] | None = None) -> int:
    """Entry point."""
    parser = argparse.ArgumentParser(
        description="Generate math-symbol glyph bitmaps for ExistOS.",
    )
    parser.add_argument(
        "--render-height",
        type=int,
        default=48,
        help="Pixel height at which to render before scaling down (default: 48).",
    )
    parser.add_argument(
        "--margin",
        type=int,
        default=12,
        help="Margin around the large render canvas (default: 12).",
    )
    parser.add_argument(
        "--threshold-bbox",
        type=int,
        default=128,
        help="Brightness threshold for bounding-box detection (default: 128).",
    )
    parser.add_argument(
        "--threshold-extract",
        type=int,
        default=160,
        help="Brightness threshold for final byte extraction (default: 160).",
    )
    parser.add_argument(
        "--stroke-width",
        type=int,
        default=1,
        help="Optional stroke width in pixels to thicken glyphs (default: 1). "
             "Set to 0 to match the original PowerShell script's unstroked rendering.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=None,
        help="Directory for debug PNGs (default: dev_tools/glyphs3).",
    )
    args = parser.parse_args(argv)

    script_dir = Path(__file__).resolve().parent
    out_dir = args.output_dir or script_dir / "glyphs3"

    font_path = find_font_path()
    font = ImageFont.truetype(str(font_path), args.render_height)

    for target_h, target_w, label in SIZES:
        print(f"// --- {label} ---")
        for code, name in zip(GLYPH_CODES, GLYPH_NAMES):
            line = render_glyph(
                code,
                name,
                target_h,
                target_w,
                label,
                font,
                out_dir,
                render_height=args.render_height,
                margin=args.margin,
                threshold_bbox=args.threshold_bbox,
                threshold_extract=args.threshold_extract,
                stroke_width=args.stroke_width,
            )
            print(line)

    print(f"Done: {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
