"""Generate bitmap glyphs for math symbols used in KhiCAS.

This is a Python replacement for the original ``gen_glyphs3.ps1`` PowerShell
script. It renders 14 math symbols from Noto Sans SC at 4 target sizes and
prints C-style byte arrays that can be pasted into
``System/applications/user/khicas/kcasporing_gl.c``.

The script follows the same algorithm as the PowerShell version (render large,
crop to bounding box, scale preserving aspect ratio, center, threshold) but uses
Pillow/FreeType instead of Windows GDI+. Because the two rasterizers differ,
the generated bytes are not guaranteed to be bit-identical to the PowerShell
output, but they are usable for the same purpose.

Run with uv from the repository root::

    uv run --project dev_tools dev_tools/gen_glyphs.py

Or from inside ``dev_tools/``::

    uv run gen_glyphs.py
"""

from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

GLYPH_NAMES = [
    "pi",
    "sqrt",
    "integ",
    "infin",
    "leq",
    "geq",
    "neq",
    "arrow",
    "alpha",
    "beta",
    "theta",
    "Sigma",
    "times",
    "divide",
]

GLYPH_CODES = [
    0x03C0,
    0x221A,
    0x222B,
    0x221E,
    0x2264,
    0x2265,
    0x2260,
    0x2192,
    0x03B1,
    0x03B2,
    0x03B8,
    0x03A3,
    0x00D7,
    0x00F7,
]

SIZES = [
    (8, 5, "5x8"),
    (12, 6, "6x12"),
    (14, 7, "7x14"),
    (16, 8, "8x16"),
]

FONT_PATH = Path(__file__).resolve().parent.parent / "fonts" / "Assets" / "unifont-17.0.04.otf"


def find_font_path(font_name: str = "") -> Path:
    """Return the bundled unifont path regardless of ``font_name``."""
    path = FONT_PATH
    if not path.exists():
        raise FileNotFoundError(f"Bundled font not found at {path}")
    return path


def find_bounding_box(img: Image.Image, threshold: int) -> tuple[int, int, int, int]:
    """Return (left, top, right, bottom) bounding box of dark pixels."""
    pixels = img.load()
    width, height = img.size
    left = width
    right = 0
    top = height
    bottom = 0

    for y in range(height):
        for x in range(width):
            if pixels[x, y] < threshold:
                if x < left:
                    left = x
                if x > right:
                    right = x
                if y < top:
                    top = y
                if y > bottom:
                    bottom = y

    return left, top, right, bottom


def extract_bytes(img: Image.Image, width: int, height: int, threshold: int) -> list[int]:
    """Convert a grayscale image into a list of bytes (bit7 = leftmost pixel)."""
    pixels = img.load()
    out: list[int] = []
    for y in range(height):
        byte_val = 0
        for x in range(width):
            if pixels[x, y] < threshold:
                byte_val |= 0x80 >> x
        out.append(byte_val)
    return out


def render_glyph(
    code: int,
    name: str,
    target_h: int,
    target_w: int,
    label: str,
    font: ImageFont.FreeTypeFont,
    out_dir: Path,
) -> str:
    """Render one glyph at native 16 px then centre-crop to target height."""
    char = chr(code)

    native = Image.new("L", (16, 16), 255)
    draw = ImageDraw.Draw(native)
    draw.text((0, -1), char, font=font, fill=0)

    # Find content rows
    TH = 128
    pixels = native.load()
    top, bottom = 16, 0
    for y in range(16):
        for x in range(16):
            if pixels[x, y] < TH:
                if y < top:
                    top = y
                if y > bottom:
                    bottom = y
                    break

    if top > bottom:  # empty
        n = target_h
        return f"    /* {name:<6} */ {','.join(['0x00'] * n)},"

    content_h = bottom - top + 1
    avail = target_h

    if avail >= content_h:
        pad = avail - content_h
        crop_top = max(0, top - pad // 2)
    else:
        excess = content_h - avail
        crop_top = top + excess // 2

    crop_bottom = crop_top + avail
    if crop_top < 0:
        crop_top, crop_bottom = 0, avail
    if crop_bottom > 16:
        crop_bottom, crop_top = 16, 16 - avail

    crop = native.crop((0, crop_top, target_w, crop_bottom))

    # Extract bytes
    cp = crop.load()
    bytes_: list[int] = []
    for y in range(crop.height):
        b = 0
        for x in range(min(target_w, crop.width)):
            if cp[x, y] < TH:
                b |= 0x80 >> x
        bytes_.append(b)

    # Debug image
    out_dir.mkdir(parents=True, exist_ok=True)
    # Centre on target canvas for debug
    debug = Image.new("L", (target_w, target_h), 255)
    ox = 0
    oy = (target_h - crop.height) // 2
    debug.paste(crop, (ox, oy))
    debug.save(out_dir / f"{name}_{label}.png")

    hex_parts = ",".join(f"0x{b:02X}" for b in bytes_)
    return f"    /* {name:<6} */ {hex_parts},"


def main() -> int:
    """Entry point."""
    script_dir = Path(__file__).resolve().parent
    out_dir = script_dir / "glyphs3"

    font_path = find_font_path()
    font = ImageFont.truetype(str(font_path), 16)

    for target_h, target_w, label in SIZES:
        print(f"// --- {label} ---")
        for code, name in zip(GLYPH_CODES, GLYPH_NAMES):
            line = render_glyph(code, name, target_h, target_w, label, font, out_dir)
            print(line)

    print(f"Done: {out_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
